language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - "pip install ."
  - "pip install -r test_requirements.txt"
script:
  - "pytest -v -s --doctest-modules tests/"
  - "flake8 httpie_asap_auth.py"
ater_success:
  - "coveralls"
